# STAGE 1: Build-Umgebung
FROM python:3.10.10-alpine AS builder

WORKDIR /app

# Installiere nur PIP, um das Image klein zu halten
RUN apk add --no-cache gcc musl-dev libffi-dev

# Kopiere nur die Requirements und installiere Abhängigkeiten
COPY requirements.txt .
RUN pip install --no-cache-dir --prefix=/install -r requirements.txt && \
    pip install --no-cache-dir --prefix=/install gunicorn

# STAGE 2: Minimales Laufzeit-Image
FROM python:3.10.10-alpine

WORKDIR /app

# Kopiere nur die benötigten Dateien aus der Build-Stage
COPY --from=builder /install /usr/local
COPY . .

# Exponiere den Port für Flask
EXPOSE 5000

# Starte den Gunicorn-Server
CMD ["gunicorn", "-b", "0.0.0.0:5000", "wsgi:app"]