# Verwende ein noch schlankeres Basis-Image
FROM python:3.10.10-alpine

# Setze das Arbeitsverzeichnis
WORKDIR /app

# Kopiere und installiere Abhängigkeiten in einem Schritt (reduziert Layer)
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt && \
    pip install --no-cache-dir gunicorn

# Kopiere den restlichen Code
COPY . .

# Exponiere den Port für Flask
EXPOSE 5000

# Starte den Gunicorn-Server
CMD ["gunicorn", "-b", "0.0.0.0:5000", "wsgi:app"]