services:

  persistent-flask:
    container_name: persistent_flask_service
    build:
      context: .
    ports:
      - 5000:5000
    volumes:
      - .:/app
    environment:
      - DATABASE_URI=mysql+mysqlconnector://root:root@msvc-db:3306/msvc
      - CHOKIDAR_USEPOLLING=true
      - FLASK_DEBUG=1
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=5000
      - FLASK_APP=app
    depends_on:
      msvc-db:
        condition: service_healthy

  msvc-db:
    image: mysql:8.4.4
    container_name: msvc-db
    restart: always
    environment:
      MYSQL_DATABASE: msvc
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - my-db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  my-db:
